apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:      
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}


  containers:
  - name: zap
    image: owasp/zap2docker-weekly
    volumeMounts:
            - name: shared-data
              mountPath: /tmp/share
    command: ["zap.sh"]
    args: [
      "-daemon",
      "-host", "127.0.0.1",
      "-port", "8081",
      "-config", "api.disablekey=true",
    ]
    ports:
    - containerPort: 8081


  - name: auth-zap-scan
    image: auth-zap-test-local:latest
    imagePullPolicy: Never
    volumeMounts:
            - name: shared-data
              mountPath: /tmp/share