name: Test Zap Scan

#I do not think this needs to be here.
on:
  workflow_dispatch:

env:
  SEQR_USER: ${{secrets.SEQR_USER}}
  SEQR_PASS: ${{secrets.SEQR_PASS}}
  DSM_USER: ${{secrets.DSM_USER}}
  DSM_PASS: ${{secrets.DSM_PASS}}
  PROXY: http://127.0.0.1
  PORT: 8081
  DDP_USER: ${{secrets.DDP_USER}}
  DDP_PASS: ${{secrets.DDP_PASS}}
  REPORT_DIR: ./tmp
  DEBUG: True
  CODEDX_API_KEY: ${{secrets.CODEDX_API_KEY}}


jobs:
  scan:
    runs-on: self-hosted
    

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . -t bundledzap
      - name: Test
        run: docker run --rm -e SEQR_USER -e SEQR_PASS -e DSM_USER -e PROXY -e PORT -e DDP_USER -e DDP_PASS -e REPORT_DIR bundledzap ./launcher.sh
