name: Test Zap Scan

on:
  workflow_dispatch:

env:
  SEQR_USER: ${{secrets.SEQR_USER}}
  SEQR_PASS: ${{secrets.SEQR_PASS}}
  DSM_USER: ${{secrets.DSM_USER}}
  DSM_PASS: ${{secrets.DSM_PASS}}
  PROXY: http://127.0.0.1
  PORT: 8081
  DDP_USER: ${{secrets.DDP_USER}}
  DDP_PASS: ${{secrets.DDP_PASS}}
  DEBUG: debug
  CODEDX_API_KEY: ${{secrets.CODEDX_API_KEY}}
  DOJO_USER: ${{secrets.DOJO_USER}}
  DOJO_KEY: ${{secrets.DOJO_KEY}}
  REPORT_DIR: /tmp/reports


jobs:
  scan:
    runs-on: [self-hosted, dev-runner]
    

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build --build-arg REPORT_DIR=${REPORT_DIR} . -t bundledzap
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Test
        run: |
          mkdir ${REPORT_DIR}
          mkdir tmp/profiles/
          gcloud auth list
          