name: Zap Scan

#I do not think this needs to be here.
on:
  schedule:
  - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  SEQR_USER: ${{secrets.SEQR_USER}}
  SEQR_PASS: ${{secrets.SEQR_PASS}}
  DSM_USER: ${{secrets.DSM_USER}}
  DSM_PASS: ${{secrets.DSM_PASS}}
  PROXY: http://127.0.0.1
  PORT: 8081
  DDP_USER: ${{secrets.DDP_USER}}
  DDP_PASS: ${{secrets.DDP_PASS}}
  DEBUG: false


jobs:
  scan:
    runs-on: [self-hosted, prod]
    

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . -t bundledzap
      - name: Test
        run: docker run --rm -e SEQR_USER -e SEQR_PASS -e DSM_USER -e DSM_PASS -e PROXY -e PORT -e DDP_USER -e DDP_PASS -e DEBUG -e CODEDX_API_KEY bundledzap ./launcher.sh